version: '3.8'
services:

  db:
    image: mysql:latest
    environment:

      MYSQL_DATABASE: bd_operator
      MYSQL_USER: root
      MYSQL_PASSWORD: slimshady666
      ports:
       - "3306:3306"


  web:
    image: tomcat:latest
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment:
      JDBC_URL: jdbc:mysql://db:3306/bd_operator?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true

    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - db
