version: '3.1'

services:

  db:
    image: mysql:5.7.31
    container_name: mysql_c
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_operator
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      TZ: Europe/Moscow
    ports:
        - 3307:3306
    networks:
      - mt-network
  tomcat:
    image: tomcat:8.5.51
    container_name: tomcat

    environment:
      WAIT_HOSTS: db:3306
      TZ: Europe/Moscow
    ports:
      - 8080:8080
    networks:
      - mt-network
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      - E:/13.T-systems/Logs/Docker:/usr/local/tomcat/logs/

    depends_on:
      - db
    links:
      - db

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: Europe/Moscow
    ports:
      - 8555:8080
    networks:
      - mt-network
networks:
  mt-network:
    driver: bridge

